import Head from "next/head";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Animation page transition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, ease: "easeInOut" }}
        className="absolute top-0 left-0 w-full h-full bg-yellow-200"
      >
        <header className="absolute top-1/3 right-24">
          <h1 className="text-5xl">Home</h1>
        </header>
      </motion.main>
    </>
  );
}
